nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    version: v1
    path: webhooks/clientConfig/service/name
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    version: v1
    path: webhooks/clientConfig/service/name

namespace:
- kind: MutatingWebhookConfiguration
  group: admissionregistration.k8s.io
  version: v1
  path: webhooks/clientConfig/service/namespace
- kind: ValidatingWebhookConfiguration
  group: admissionregistration.k8s.io
  version: v1
  path: webhooks/clientConfig/service/namespace
