# This rule is not used by the project json-server-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to example.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: json-server-controller
    app.kubernetes.io/managed-by: kustomize
  name: jsonserver-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - jsonservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - jsonservers/status
  verbs:
  - get
