apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: json-server-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/msfurusa/json-server-controller.git
    targetRevision: main
    path: config/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: json-server-controller-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
