apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - ../manifests

images:
  - name: controller
    newName: ttl.sh/json-server-controller-controller
    newTag: 1h

patchesStrategicMerge:
  - jsonserver-image-patch.yaml
