apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - ../manifests

images:
  - name: controller
    newName: controller
    newTag: latest

patchesStrategicMerge:
  - jsonserver-image-patch.yaml
