apiVersion: v1
kind: Service
metadata:
  name: app-my-server
  namespace: default
  labels:
    app: app-my-server
spec:
  selector:
    app: app-my-server
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
